### ISSUE TITLE
Allow user defined functions capability

### ISSUE THREAD

**Issue by septs** [bep/godartsass#10]
Allow hugo define hugo-specific built-in sass functions

Improve development experience (simplify reference resource files)

Replaced by https://github.com/bep/golibsass/issues/7

https://github.com/bep/godartsass/blob/9f9f1c1aeb19fa45147bf1ca123e73a8dec85e66/internal/embeddedsass/embedded_sass.proto#L537-L568

https://github.com/bep/godartsass/blob/9f9f1c1aeb19fa45147bf1ca123e73a8dec85e66/internal/embeddedsass/embedded_sass.proto#L220-L239

**Comment by septs** [comment]
https://github.com/sass/embedded-host-node/blob/main/lib/src/function-registry.ts

**Comment by septs** [comment]
i want use sass function, improve developer experience:

port resources series api into sass compiler, simplify use image file steps

**Comment by bep** [comment]
>port resources series api into sass compiler, simplify use image file steps

Next Hugo allows you pass the URL of these image resources as variables to Dart Sass. How is your suggested approach better? To me it sounds

* Like a very tight coupling between the stylesheet and Hugo's API
* A fairly ineffective way of doing it compared to just passing in some string values on `Execute``

**Comment by bep** [comment]
Note, that I don't mind adding a "functions API" to this library as long as someone could

* Give me one or more great use cases for it.
* Suggest a good implementation.

**Comment by septs** [comment]
```scss
.example {
  --use-file-with-function: resources.get(file-path);
  // vs
  --use-file-with-variable: $injected-file-name; // define separation
}
```

**Comment by bep** [comment]
```
.example {
  --use-file-with-function: resources-get(file-path); // needs Hugo to work, designer needs to understand Hugo's API, will cost one RPC invocation
  // vs
  --use-file-with-variable: $injected-file-name; // can be defined by Hugo or a stylesheet
}
```
