### ISSUE TITLE
Keeping it up to date

### ISSUE THREAD

**Issue by MelihDarcanxyz** [bep/godartsass#13]
It may be a noob question but I'm wondering how can we keep this up to date to use with Hugo.

Packaging it for major linux distributions would be very nice. For example, if we could have it on AUR, it could be much easier to handle updates. Other way, we have to check for it and manually update the package.

If there's a better way, I'm all ears.

**Comment by bep** [comment]
>It may be a noob question but I'm wondering how can we keep this up to date to use with Hugo.

What do you mean by keeping this "up to date"? This implements parts of a protocol which very rarely changes and if it does it would be very surprising if it had backwards incompatible breakage. So the "keeping it up to date" here is to keep the test setup pointing to a recent (or newest) release, which I don't think I want to spend time on automating (as it happens so rarely).

>Packaging it for major linux distributions would be very nice. 

This is Go library, there's nothing to package. 

I assume you may be meaning that you want us (me) to somehow package the Dart Sass Embedded binary, and I agree, that would be useful, but I don't think Go has a good way of doing that in a simple and secure way. But I'm happy to be proven wrong.

**Comment by MelihDarcanxyz** [comment]
I don't know how go package is different from any other language's package. Like python or haskell. They all have packages to install from package managers, so we can manage them.

**Comment by bep** [comment]
>I don't know how go package is different from any other language's package. Like python or haskell. They all have packages to install from package managers, so we can manage and keep track of them.

Hugo (and most go programs) uses Go Modules:

https://github.com/gohugoio/hugo/blob/master/go.mod#L13

That uses Git semver tags (aka GitHub releases) as the foundation. So whenever this library creates a new release, Hugo gets notified.
