### ISSUE TITLE
Syntax of imported files isn't provided.

### ISSUE THREAD

**Issue by CamilleScholtz** [bep/godartsass#14]
Because of this imported files that are written in SASS/INDENTED rather than SCSS get interpreted as being SCSS, this makes the compiler fail.

Here `Syntax` should be given, with the syntax of the imported file in question:
https://github.com/bep/godartsass/blob/main/transpiler.go#L359

Way to reproduce this with Hugo: https://discourse.gohugo.io/t/dart-sass-embedded-does-not-build-valid-sass-files/43184

**Comment by bep** [comment]
Sorry for the late response, I will have look at this re. some related work in doing in this department.
