### ISSUE TITLE
Executeable file renamed

### ISSUE THREAD

**Issue by shyim** [bep/godartsass#15]
[Dart-sass-embedded is dead](https://github.com/sass/dart-sass-embedded/commit/4190c318d42a013414a565195e23e0652fb5651f), it's now part of `dart-sass` itself.

**Comment by bep** [comment]
There's no release in the dart-sass repo yet, so nothing do but wait. I'm closing this for now. Please reopen when you can download a binary that takes the `--embedded` flag.
