### ISSUE TITLE
sassTranspiler.Execute returns "Unexpected EOF" for indented sass.

### ISSUE THREAD

**Issue by RyanPrentiss** [bep/godartsass#21]
The following returns `Unexpected EOF` no matter the indented sass input. Is this a bug, or am I going about this incorrectly?

```
import (
	"log"
	"os"

	"github.com/bep/godartsass/v2"
)

func Compile() {
	sassTranspiler, err := godartsass.Start(godartsass.Options{})
	if err != nil {
		log.Fatal(err)
	}
	defer sassTranspiler.Close()

	result, err := sassTranspiler.Execute(godartsass.Args{
		Source:          "./_index.sass",
		OutputStyle:     godartsass.OutputStyleCompressed,
		SourceSyntax:    godartsass.SourceSyntaxSASS,
		EnableSourceMap: true,
	})
	if err != nil {
		log.Fatal(err)
	}

	os.WriteFile("../assets/style.css", []byte(result.CSS), 0644)
	os.WriteFile("../assets/style.css.map", []byte(result.SourceMap), 0644)
}
```

_Copilot told me to scrap it and use_ `exec.Command("sass" ...)`

**Comment by bep** [comment]
>Copilot told me to scrap it and use exec.Command("sass" ...)

Got to love AI.

As to the issue, your usage looks correct, but I have not seen any similar reports in Hugo.

I suspect you need to upgrade your Sass version. The protocol used in this library is relatively new, see
https://gohugo.io/functions/resources/tocss/#installation-overview
