### ISSUE TITLE
Upgrade to v3 of the protocol

### ISSUE THREAD

**Issue by juanolon** [bep/godartsass#28]
Hello,
I get the error `proto: cannot parse reserved wire type` when compiling a sass Source.
I have tried with dart-sass versions `1.79.2` and `1.79.3`. 
I guess, there is a version miss match for the proto protocol.. What version is currently used?
Thanks

**Comment by bep** [comment]
>What version is currently used?

v2. I just had a look and they released a v3 a few weeks ago. If yo downgrade to <= 1.78.* it should work.

**Comment by bep** [comment]
>v2. I just had a look and they released a v3 a few weeks ago. If yo downgrade to <= 1.78.* it should work.

As a side note, I find it rather odd that Sass uses semver major versions for the protocol that does not trickle up to the major version of the containing library.

**Comment by juanolon** [comment]
I did the downgrade, but still getting the same error. I even tried 1.63.2 (as in the `workflows/test.yaml`

**Comment by bep** [comment]
@juanolon then I suspect it must be "something else". I upgraded to the latest Sass versions locally (and in a PR) and the only failing test is the one testing for the protocol version string, and I think we have a pretty good test coverage.

**Comment by juanolon** [comment]
At the end, seems that i was using the wrong version of the library. Since i was starting the server with a custom `sass` path, i never did see the error
```go
t, err := godartsass.Start(godartsass.Options{
	DartSassEmbeddedFilename: sassPath,
})
```
When i remove it, I notice that the required sass path was `dart-sass-embedded`.

Installing the newer version
```bash
go get github.com/bep/godartsass/v2
```
solve the problem. I believe version 2 would be a more fitting default, isn't it?
