### ISSUE TITLE
Deadlocks in Execute

### ISSUE THREAD

**Issue by benlife5** [bep/godartsass#31]
Hi,

We've occasionally been seeing deadlocks in the Execute function. Seems to block the timeout functionality from triggering too. Unfortunately, I don't have a way to reproduce, but I've added additional logging for when it happens and will update this issue if I get more details.

Our usage: 
```
func (gen *SassCompiler) Compile(scss string) (string, error) {
	if len(scss) > 0 {
		res, err := transpiler.Execute(godartsass.Args{
			Source:         scss,
			OutputStyle:    godartsass.OutputStyleCompressed,
			ImportResolver: scssResolver{},
		})
		if err != nil {
			return "", yerrors.Wrap(err)
		}
		return strings.TrimPrefix(res.CSS, "\ufeff"), nil
	}

	return "", nil
}
```

Relevant part of the goroutine trace:
```
1367 @ ...
#   0x474724    sync.runtime_SemacquireMutex+0x24                                       GOROOT/src/runtime/sema.go:77
#   0x48421c    sync.(*Mutex).lockSlow+0x15c                                            GOROOT/src/sync/mutex.go:171
#   0x22da651   sync.(*Mutex).Lock+0x71                                             GOROOT/src/sync/mutex.go:90
#   0x22da626   github.com/bep/godartsass/v2.(*Transpiler).sendInboundMessage+0x46                      external/com_github_bep_godartsass_v2/transpiler.go:506
#   0x22da544   github.com/bep/godartsass/v2.(*Transpiler).newCall+0x2a4                            external/com_github_bep_godartsass_v2/transpiler.go:502
#   0x22d8904   github.com/bep/godartsass/v2.(*Transpiler).Execute+0xa4                             external/com_github_bep_godartsass_v2/transpiler.go:227
#   0x22e29f7   path/to/scsscompiler/lpsass.(*SassCompiler).Compile+0xd7             path/to/scsscompiler/lpsass/libsass.go:79
```

Occurred with version 2.0.0, I've just upgraded to 2.3.0 and will update if it happens again

**Comment by bep** [comment]
Thanks for the report. I'm assuming #32 will fix this, but I will leave this issue open. Note that this will not fix the underlying issue (a panic?).

**Comment by benlife5** [comment]
Thanks for the quick fix! We'll update and monitor

**Comment by benlife5** [comment]
@bep I've been running into issues updating the package. Is it possible that `go.mod` should have been updated to require a later version of `google.golang.org/protobuf` as part of https://github.com/bep/godartsass/issues/28? It looks like protobuf removed that panic after 1.30 and `internal/embeddedsass/embedded_sass.pb.go` was generated with 1.35.

This is the panic I'm getting:
```
panic: not supported

goroutine 60 [running]:
google.golang.org/protobuf/internal/impl.Export.MessageStateOf({}, {0xc00132db10?, 0x474613?})
	external/org_golang_google_protobuf/internal/impl/pointer_reflect.go:198 +0x25
github.com/bep/godartsass/v2/internal/embeddedsass.(*InboundMessage).ProtoReflect(0x415354?)
	external/com_github_bep_godartsass_v2/internal/embeddedsass/embedded_sass.pb.go:458 +0x3c```

**Comment by bep** [comment]
>Is it possible that go.mod should have been updated to require a later version of google.golang.org/protobuf as part of https://github.com/bep/godartsass/issues/28?

I don't know, but I could/should certainly bump that/the dependenccies. I will do that, thanks for the input.

**Comment by bep** [comment]
See https://github.com/bep/godartsass/releases/tag/v2.3.2

**Comment by bep** [comment]
@benlife5 does this mean that this issue is resolved and can be closed?

**Comment by benlife5** [comment]
I think so. The deadlocks occurs infrequently so I can't say for certain that it is no longer happening but I'm good with closing this item and I can reopen if it recurs.

**Comment by samuel-280589** [comment]
https://github.com/bep/godartsass/issues/31#issue-2696068740
